"""Write `frontend/src/api/presentation.js` from `scanner/presentation.py`.

R15-ARCH-1. The presentation model is declared once, in Python, because that is where
`CheckResult` lives and where the CLI renderer reads it. The browser needs the same
declarations, and a hand-typed copy of them is the exact defect the model exists to close
— four filings in three rounds came out of two renderers maintained against each other by
eye.

So it is GENERATED, into `frontend/src/api/`, which is the directory
`make check-generated` already diffs after `make generate-client`. A stale copy is a red
gate, by the mechanism the zod mirror has used since §4.5 — no new gate, no new rule to
remember, and the same failure message a stale serializer mirror produces.

WHAT IS NOT GENERATED: the sanitizers. They are a Python transform at the TEXT medium's
boundary, and the DOM is not a control-character interpreter — React escapes what it
renders, an ESC byte in a text node is an ESC byte and paints nothing. Generating a
second implementation of a security-relevant transform to sit where it has nothing to do
would be a copy with a gate around it, which is not the same thing as one spelling. The
one place the class is genuinely wanted on the web is bidi/zero-width DISPLAY spoofing in
a filename, which is a real and different finding, lower severity than the terminal one,
and it wants its own commit rather than a rider on this one.
"""
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "frontend" / "src" / "api" / "presentation.js"

HEADER = """// GENERATED by scripts_dev/generate_presentation.py from scanner/presentation.py.
// Do not edit: `make generate-client` rewrites it and `make check-generated` fails on a
// stale copy, the same way it does for the zod mirror next to it.
//
// This is the presentation MODEL for one CheckResult — which fields render, in what
// order, under which label, hidden at which tiers — shared by `hub/__main__.py`'s text
// renderer and `frontend/src/Readiness.jsx`'s CheckBody so the two cannot disagree about
// what a check says. How each medium says it stays with each medium.
"""


def render():
    sys.path.insert(0, str(REPO))
    from scanner import presentation

    fields = json.dumps([dict(f) for f in presentation.CHECK_FIELDS], indent=2)
    gates = json.dumps({k: list(v) for k, v in presentation.TIER_GATES.items()}, indent=2)
    # R20 / dom-bidi-display: the SAME character class the CLI and the two JSON exits
    # escape against, generated so the browser's display sanitizer is not a second
    # hand-written copy of a security-relevant range list (the round-15 concern).
    # `CONTROL_CLASS` is the regex char-class BODY (`json.dumps` doubles its backslashes
    # into a JS string literal); `TEXT_CONTROL_CLASS` is the same minus U+000A, for prose
    # that keeps the server's own line breaks — the `safe_path`/`safe_text` split.
    control = json.dumps(presentation.CONTROL_CLASS)
    text_control = json.dumps(presentation.TEXT_CONTROL_CLASS)
    return (f"{HEADER}\nexport const CHECK_FIELDS = {fields};\n\n"
            f"export const TIER_GATES = {gates};\n\n"
            f"export const CONTROL_CLASS = {control};\n\n"
            f"export const TEXT_CONTROL_CLASS = {text_control};\n")


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv:
        # The `mutation_gate.py` / `sim_fixture_payloads.py` precedent: a generator that
        # emits one whole file takes no arguments, and an argument it silently ignored
        # would be somebody believing they had scoped it.
        print(f"generate_presentation: refusing to run with arguments {argv} — it writes "
              f"{OUT.relative_to(REPO)} from scanner/presentation.py and takes none.",
              file=sys.stderr)
        return 2
    OUT.write_text(render(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
