"""Write `frontend/src/api/action_tiers.js` from `core/actions.py`.

Same directory `make check-generated` already diffs after `make generate-client`.
"""
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "frontend" / "src" / "api" / "action_tiers.js"

HEADER = """// GENERATED by scripts_dev/generate_actions.py from core/actions.py.
// Do not edit: `make generate-client` rewrites it and `make check-generated` fails on a
// stale copy, the same way it does for the zod mirror next to it.
"""


def render():
    sys.path.insert(0, str(REPO))
    from core.actions import ACTION_TIERS

    table = json.dumps([dict(row) for row in ACTION_TIERS], indent=2)
    return f"{HEADER}\nexport const ACTION_TIERS = {table};\n"


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv:
        print(
            f"generate_actions: refusing to run with arguments {argv} — it writes "
            f"{OUT.relative_to(REPO)} from core/actions.py and takes none.",
            file=sys.stderr,
        )
        return 2
    OUT.write_text(render(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
