# Generated by Django 5.2.16 on 2026-08-02 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ui", "Ui"),
                            ("api", "Api"),
                            ("celery", "Celery"),
                            ("reconciler", "Reconciler"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("action", models.SlugField(max_length=64)),
                ("object_type", models.CharField(blank=True, max_length=64)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("security", "Security"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                ("partner_id_stub", models.IntegerField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-ts"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="core_audite_object__bbabc4_idx",
                    )
                ],
            },
        ),
    ]
