# Generated by Django 5.2.17 on 2026-08-08 21:16

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recoverycode_ws_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('source_kind', models.CharField(choices=[('git', 'Git'), ('local_path', 'Local Path')], default='git', max_length=16)),
                ('git_url', models.CharField(blank=True, max_length=2048, validators=[core.validators.validate_git_url])),
                ('git_ref', models.CharField(default='main', max_length=255)),
                ('local_path', models.CharField(blank=True, max_length=1024)),
                ('scan_report', models.JSONField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('scan_source_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('domain', models.CharField(blank=True, max_length=253)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='uniq_site_name')],
            },
        ),
    ]
