# Generated by Django 5.2.17 on 2026-08-20 14:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='config_stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='deploy_policy',
            field=models.CharField(choices=[('auto', 'Auto'), ('confirm', 'Confirm'), ('windowed', 'Windowed')], default='auto', max_length=16),
        ),
        migrations.AddField(
            model_name='site',
            name='deploy_strategy',
            field=models.CharField(choices=[('blue_green', 'Blue Green'), ('recreate', 'Recreate')], default='blue_green', max_length=16),
        ),
        migrations.AddField(
            model_name='site',
            name='deploy_window_cron',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='site',
            name='exposure',
            field=models.CharField(choices=[('public', 'Public'), ('mesh_only', 'Mesh Only')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='site',
            name='liveness_path',
            field=models.CharField(blank=True, default='/healthz', max_length=256),
        ),
        migrations.AddField(
            model_name='site',
            name='maintenance_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='readiness_path',
            field=models.CharField(blank=True, default='/healthz.ready', max_length=256),
        ),
        migrations.AddField(
            model_name='site',
            name='reconcile_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='warmup_timeout_s',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.CreateModel(
            name='OperationLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('site', 'Site'), ('target', 'Target')], max_length=16)),
                ('object_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('deploy', 'Deploy'), ('provision', 'Provision'), ('reconcile', 'Reconcile')], max_length=16)),
                ('holder', models.CharField(max_length=128)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'object_id', 'kind'), name='uniq_operationlock_scope_object_kind')],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ssh', 'Ssh')], default='ssh', max_length=16)),
                ('host', models.CharField(max_length=253)),
                ('ssh_user', models.CharField(default='root', max_length=64)),
                ('ssh_key_ref', models.CharField(blank=True, default='', max_length=64)),
                ('host_key_fingerprint', models.CharField(blank=True, default='', max_length=256)),
                ('lifecycle', models.CharField(choices=[('permanent', 'Permanent'), ('ephemeral', 'Ephemeral')], default='permanent', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('error', 'Error'), ('decommissioned', 'Decommissioned')], default='pending', max_length=16)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='core.networkzone')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='primary_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_sites', to='core.target'),
        ),
        migrations.CreateModel(
            name='DnsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
                ('rtype', models.CharField(max_length=16)),
                ('value', models.CharField(max_length=1024)),
                ('observed_value', models.CharField(blank=True, default='', max_length=1024)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='core.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'name', 'rtype'), name='uniq_dnsrecord_site_name_rtype')],
            },
        ),
        migrations.CreateModel(
            name='SiteVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('container_path', models.CharField(max_length=512)),
                ('backup_policy', models.CharField(choices=[('none', 'None'), ('directory_sync', 'Directory Sync')], default='none', max_length=32)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='core.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'name'), name='uniq_sitevolume_site_name')],
            },
        ),
        migrations.CreateModel(
            name='SiteInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_image_tag', models.CharField(blank=True, default='', max_length=256)),
                ('desired_state', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('absent', 'Absent')], default='absent', max_length=16)),
                ('observed_state', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('absent', 'Absent'), ('unhealthy', 'Unhealthy'), ('warming', 'Warming')], default='absent', max_length=16)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('internal_port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20000), django.core.validators.MaxValueValidator(29999)])),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.site')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.target')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target', 'internal_port'), name='uniq_siteinstance_target_port'), models.CheckConstraint(condition=models.Q(('internal_port__gte', 20000), ('internal_port__lte', 29999)), name='siteinstance_internal_port_range')],
            },
        ),
    ]
