# Generated by Django 5.2.17 on 2026-08-21 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_networkzone_site_config_stale_site_deploy_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('postgres', 'Postgres'), ('sqlite_file', 'Sqlite File'), ('directory_sync', 'Directory Sync')], max_length=32)),
                ('schedule', models.CharField(default='0 2 * * *', max_length=128)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_units', to='core.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'kind'), name='uniq_backupunit_site_kind')],
            },
        ),
    ]
