# Generated by Django 5.2.17 on 2026-08-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_backupunit_and_secret_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='collect_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='collect_log_inode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='collect_log_offset',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='target',
            name='collect_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationlock',
            name='kind',
            field=models.CharField(choices=[('deploy', 'Deploy'), ('provision', 'Provision'), ('reconcile', 'Reconcile'), ('collect', 'Collect')], max_length=16),
        ),
    ]
