# Generated by Django 5.2.17 on 2026-08-21 15:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_networkzone_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hub_down', 'Hub Down'), ('restore_clean', 'Restore Clean'), ('reaper', 'Reaper'), ('pager', 'Pager')], max_length=32)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=16)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('results', models.JSONField(default=core.models._default_checkrun_results)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'due_at'], name='core_checkr_kind_ce2d4c_idx')],
            },
        ),
    ]
