# Generated by Django 5.2.17 on 2026-08-22 12:09
"""Phase 3 schema wave (design note §2, Task 1).

Upgrade-path decision (task review, 2026-08-22): the new
site_public_requires_dns_zone constraint validates EXISTING rows, and a
pre-existing public Site with no dns_zone would fail the ALTER with a bare
IntegrityError. No backfill is honest — the Hub cannot invent which provider
zone a site belongs to (D-033), and silently flipping sites to mesh_only
would change their exposure behind the operator's back. So the fail-closed
shape is: _refuse_public_sites_without_dns_zone runs BEFORE the constraint
lands and aborts the migration with a named, actionable error listing the
offending sites and the two honest fixes (attach a DnsZone, or set the site
mesh_only), leaving the database untouched at 0008.
"""

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _refuse_public_sites_without_dns_zone(apps, schema_editor):
    """Named refusal for rows the incoming check constraint would reject."""
    Site = apps.get_model("core", "Site")
    offenders = list(
        Site.objects.using(schema_editor.connection.alias)
        .filter(dns_zone__isnull=True)
        .exclude(exposure="mesh_only")
        .values_list("pk", "name")
    )
    if offenders:
        listed = ", ".join(f"#{pk} {name!r}" for pk, name in offenders)
        raise RuntimeError(
            "core.0009_phase3 refuses to add the site_public_requires_dns_zone "
            f"constraint: {len(offenders)} public site(s) have no DnsZone "
            f"({listed}). Before re-running migrate, either connect a DNS "
            "account and attach a DnsZone to each listed site, or set the "
            "site's exposure to mesh_only. No automatic backfill exists: the "
            "Hub cannot invent which provider zone a site belongs to "
            "(D-033/D-034)."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_checkrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('ntfy', 'Ntfy'), ('email', 'Email')], max_length=16)),
                ('severity', models.CharField(choices=[('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], max_length=8)),
                ('backend', models.CharField(blank=True, default='', max_length=64)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ok', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=128, unique=True)),
                ('consecutive_fail', models.PositiveIntegerField(default=0)),
                ('consecutive_ok', models.PositiveIntegerField(default=0)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('transitions', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='DnsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('cloudflare', 'Cloudflare')], default='cloudflare', max_length=32)),
                ('label', models.CharField(max_length=128)),
                ('dns_token_ref', models.CharField(blank=True, default='', max_length=64)),
                ('edge_token_ref', models.CharField(blank=True, default='', max_length=64)),
                ('origin_ca_key_ref', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_engine', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], max_length=8)),
                ('entity', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(blank=True, default='')),
                ('fix_action', models.CharField(blank=True, default='', max_length=256)),
                ('state', models.CharField(choices=[('open', 'Open'), ('acked', 'Acked'), ('resolved', 'Resolved'), ('accepted', 'Accepted')], default='open', max_length=16)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('fingerprint', models.CharField(max_length=128, unique=True)),
                ('accepted_reason', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TlsCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('origin_cert', 'Origin Cert'), ('uploaded', 'Uploaded'), ('auto', 'Auto'), ('hub_dns01', 'Hub Dns01')], max_length=16)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('key_ref', models.CharField(blank=True, default='', max_length=64)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_start', models.DateTimeField(db_index=True)),
                ('granularity', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day')], default='minute', max_length=16)),
                ('requests', models.BigIntegerField(default=0)),
                ('bytes', models.BigIntegerField(default=0)),
                ('status_counts', models.JSONField(blank=True, default=dict)),
                ('sampled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UptimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=128)),
                ('kind', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='proxied',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checkrun',
            name='kind',
            field=models.CharField(choices=[('hub_down', 'Hub Down'), ('restore_clean', 'Restore Clean'), ('reaper', 'Reaper'), ('pager', 'Pager'), ('cf_token_scope', 'Cf Token Scope'), ('cert_expiry', 'Cert Expiry')], max_length=32),
        ),
        migrations.CreateModel(
            name='DnsZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
                ('provider_zone_id', models.CharField(blank=True, default='', max_length=64)),
                ('purpose', models.CharField(choices=[('prod', 'Prod'), ('test', 'Test')], default='prod', max_length=16)),
                ('proxied_default', models.BooleanField(default=True, help_text="A Cloudflare capability surfaced by the provider's capabilities() — not a provider-neutral setting.")),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='core.dnsaccount')),
            ],
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.dnszone'),
        ),
        migrations.AddField(
            model_name='site',
            name='dns_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='core.dnszone'),
        ),
        # Fail closed with a named, actionable error instead of letting the
        # constraint ALTER die on pre-existing rows (see module docstring).
        migrations.RunPython(
            _refuse_public_sites_without_dns_zone,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(('exposure', 'mesh_only'), ('dns_zone__isnull', False), _connector='OR'), name='site_public_requires_dns_zone'),
        ),
        migrations.AddField(
            model_name='alertdelivery',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.finding'),
        ),
        migrations.AddField(
            model_name='tlscertificate',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tls_certificates', to='core.site'),
        ),
        migrations.AddField(
            model_name='trafficstat',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_stats', to='core.site'),
        ),
        migrations.AddConstraint(
            model_name='dnszone',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='uniq_dnszone_account_name'),
        ),
    ]
