# Generated by Django 5.2.17 on 2026-08-28 02:40

import core.models.workspace
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_workspace_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='workspace',
            field=models.ForeignKey(default=core.models.workspace.default_workspace_id, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='dnsaccount',
            name='workspace',
            field=models.ForeignKey(default=core.models.workspace.default_workspace_id, on_delete=django.db.models.deletion.CASCADE, related_name='dns_accounts', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='workspace',
            field=models.ForeignKey(default=core.models.workspace.default_workspace_id, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='networkzone',
            name='workspace',
            field=models.ForeignKey(default=core.models.workspace.default_workspace_id, on_delete=django.db.models.deletion.CASCADE, related_name='network_zones', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='operationlock',
            name='workspace',
            field=models.ForeignKey(default=core.models.workspace.default_workspace_id, on_delete=django.db.models.deletion.CASCADE, related_name='operation_locks', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='workspace',
            field=models.ForeignKey(default=core.models.workspace.default_workspace_id, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(default=core.models.workspace.default_workspace_id, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.workspace'),
        ),
    ]
