# Generated by Django 5.2.17 on 2026-08-28

import core.models.workspace
import django.db.models.deletion
from django.db import migrations, models


def backfill_alert_state_workspace(apps, schema_editor):
    AlertState = apps.get_model("core", "AlertState")
    Finding = apps.get_model("core", "Finding")
    Workspace = apps.get_model("core", "Workspace")
    default = Workspace.objects.filter(slug="default").first()
    if default is None:
        default = Workspace.objects.create(name="Default workspace", slug="default")
    for state in AlertState.objects.all():
        finding = Finding.objects.filter(fingerprint=state.fingerprint).first()
        if finding is not None:
            state.workspace_id = finding.workspace_id
            state.save(update_fields=["workspace_id"])
        elif state.workspace_id is None:
            state.workspace_id = default.pk
            state.save(update_fields=["workspace_id"])


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_workspace_cascade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="fingerprint",
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=("workspace", "fingerprint"),
                name="finding_workspace_fingerprint_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["workspace", "state", "severity"],
                name="core_findin_workspa_idx",
            ),
        ),
        migrations.AddField(
            model_name="alertstate",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_states",
                to="core.workspace",
            ),
        ),
        migrations.RunPython(backfill_alert_state_workspace, noop),
        migrations.AlterField(
            model_name="alertstate",
            name="workspace",
            field=models.ForeignKey(
                default=core.models.workspace.default_workspace_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_states",
                to="core.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="alertstate",
            name="fingerprint",
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name="alertstate",
            constraint=models.UniqueConstraint(
                fields=("workspace", "fingerprint"),
                name="alertstate_workspace_fingerprint_uniq",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="scope",
            field=models.CharField(default="workspace", max_length=16),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="chain_version",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_events",
                to="core.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["workspace", "ts"],
                name="core_audite_workspa_ts_idx",
            ),
        ),
        migrations.CreateModel(
            name="AuditChainHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(default="workspace", max_length=16)),
                ("last_hash", models.CharField(blank=True, default="", max_length=64)),
                ("version", models.PositiveSmallIntegerField(default=2)),
                (
                    "last_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.auditevent",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_chain_heads",
                        to="core.workspace",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="auditchainhead",
            constraint=models.UniqueConstraint(
                fields=("scope", "workspace"),
                name="audit_chain_head_scope_workspace_uniq",
            ),
        ),
    ]
