# Generated by Django 5.2.17 on 2026-08-08 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_project_site'),
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=128)),
                ('value', models.JSONField(blank=True, null=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('secret_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vault.secret')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'question_id'), name='uniq_answer_site_question'), models.CheckConstraint(condition=models.Q(models.Q(('is_secret', False), ('secret_ref__isnull', True)), models.Q(('is_secret', True), ('secret_ref__isnull', False), ('value__isnull', True)), _connector='OR'), name='answer_secret_xor_value')],
            },
        ),
    ]
