// GENERATED by scripts_dev/generate_presentation.py from scanner/presentation.py.
// Do not edit: `make generate-client` rewrites it and `make check-generated` fails on a
// stale copy, the same way it does for the zod mirror next to it.
//
// This is the presentation MODEL for one CheckResult — which fields render, in what
// order, under which label, hidden at which tiers — shared by `hub/__main__.py`'s text
// renderer and `frontend/src/Readiness.jsx`'s CheckBody so the two cannot disagree about
// what a check says. How each medium says it stays with each medium.

export const CHECK_FIELDS = [
  {
    "key": "detail",
    "label": "",
    "kind": "prose"
  },
  {
    "key": "refused_paths",
    "label": "Did not read:",
    "kind": "paths"
  },
  {
    "key": "fix_hint",
    "label": "Fix:",
    "kind": "prose"
  }
];

export const TIER_GATES = {};

export const CONTROL_CLASS = "\\x00-\\x1f\\x7f\\x80-\\x9f\\u2028\\u2029\\u200b-\\u200f\\u202a-\\u202e\\u2066-\\u2069\\u061c\\u2060-\\u2064\\ufeff\\u180e\\u206a-\\u206f\\ufe00-\\ufe0f\\ufff9-\\ufffb\udb40\udc01\udb40\udc20-\udb40\udc7f\udb40\udd00-\udb40\uddef\\udc80-\\udcff";

export const TEXT_CONTROL_CLASS = "\\x00-\\x09\\x0b-\\x1f\\x7f\\x80-\\x9f\\u2028\\u2029\\u200b-\\u200f\\u202a-\\u202e\\u2066-\\u2069\\u061c\\u2060-\\u2064\\ufeff\\u180e\\u206a-\\u206f\\ufe00-\\ufe0f\\ufff9-\\ufffb\udb40\udc01\udb40\udc20-\udb40\udc7f\udb40\udd00-\udb40\uddef\\udc80-\\udcff";
