// GENERATED by scripts_dev/generate_presentation.py from scanner/presentation.py.
// Do not edit: `make generate-client` rewrites it and `make check-generated` fails on a
// stale copy, the same way it does for the zod mirror next to it.
//
// This is the presentation MODEL for one CheckResult — which fields render, in what
// order, under which label, hidden at which tiers — shared by `hub/__main__.py`'s text
// renderer and `frontend/src/Readiness.jsx`'s CheckBody so the two cannot disagree about
// what a check says. How each medium says it stays with each medium.

export const CHECK_FIELDS = [
  {
    "key": "detail",
    "label": "",
    "kind": "prose"
  },
  {
    "key": "refused_paths",
    "label": "Did not read:",
    "kind": "paths"
  },
  {
    "key": "fix_hint",
    "label": "Fix:",
    "kind": "prose"
  }
];

export const TIER_GATES = {};
