/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description CSRF-protected even though unauthenticated (round-1 finding: login-CSRF —
         *     a cross-site page must not be able to log the victim into an attacker account).
         *     The SPA fetches /api/auth/me/ on load, which plants the CSRF cookie.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Session hydration for the SPA. AllowAny: the anonymous response is the
         *     SPA's pre-login bootstrap and plants the CSRF cookie (get_token) so the
         *     login POST itself can be CSRF-checked.
         */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/totp/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_totp_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/totp/enroll/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_totp_enroll_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/webauthn/login/begin/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Unauthenticated begin so login can take a WebAuthn assertion as 2FA. */
        post: operations["auth_webauthn_login_begin_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo-jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["demo_jobs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topic}/snapshot/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Snapshot-then-stream (§D7): every snapshot returns {seq, data} from the same counter. */
        get: operations["topics_snapshot_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aws/connect/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_aws_connect_retrieve"];
        put?: never;
        post: operations["v1_aws_connect_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cloudflare/connect/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_cloudflare_connect_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dns-accounts/{account_id}/origin-ca-plant/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_dns_accounts_origin_ca_plant_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_findings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_findings_retrieve_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{id}/transition/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_findings_transition_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/first-run/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_first_run_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instance/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description T1: two passkeys + recent WebAuthn touch + type-the-name, then enroll. */
        get: operations["v1_instance_create_retrieve"];
        put?: never;
        /** @description T1: two passkeys + recent WebAuthn touch + type-the-name, then enroll. */
        post: operations["v1_instance_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Table-backed map.graph snapshot (§D7 / MAP-96-GRAPH-V1). */
        get: operations["v1_map_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partner-api/kill-switch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description T1 partner.api_kill_switch: type partner-api. Enable when OFF, never a toggle. */
        post: operations["v1_partner_api_kill_switch_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET is the operator list (no secrets). POST is T1 partner.create. */
        get: operations["v1_partners_retrieve"];
        put?: never;
        /** @description GET is the operator list (no secrets). POST is T1 partner.create. */
        post: operations["v1_partners_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET never echoes hubk_ or whsec_. */
        get: operations["v1_partners_retrieve_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/{id}/destination-rank/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description T2 partner.destination_rank. Own-server without tunnel is a Finding. */
        post: operations["v1_partners_destination_rank_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/{id}/suspend/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description T1 partner.suspend: type the slug, then stop + detach + revoke. */
        post: operations["v1_partners_suspend_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description What the readiness screen renders its left column from (F7-lite).
         *
         *     tier COUNTS here, full check bodies from /readiness/ — the list stays cheap when
         *     projects grow. manifest_current answers the one freshness question the data model
         *     can answer honestly: does the latest manifest correspond to the CURRENT scan?
         *     (A true warnings-diff-since-last-manifest would need the prior report stored,
         *     which it isn't — noted in the F7 design decision rather than faked.)
         *
         *     POST creates Project + Site in one transaction and binds dns_zone /
         *     primary_target from the eligible fleet (I-purpose / I-target).
         */
        get: operations["v1_projects_list"];
        put?: never;
        /**
         * @description What the readiness screen renders its left column from (F7-lite).
         *
         *     tier COUNTS here, full check bodies from /readiness/ — the list stays cheap when
         *     projects grow. manifest_current answers the one freshness question the data model
         *     can answer honestly: does the latest manifest correspond to the CURRENT scan?
         *     (A true warnings-diff-since-last-manifest would need the prior report stored,
         *     which it isn't — noted in the F7 design decision rather than faked.)
         *
         *     POST creates Project + Site in one transaction and binds dns_zone /
         *     primary_target from the eligible fleet (I-purpose / I-target).
         */
        post: operations["v1_projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/readiness/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The three-tier readiness report (§5.3), tiered server-side.
         *
         *     Tiering happens here rather than in the client so the CLI, the UI and the pipeline
         *     all agree on what counts as a blocker.
         */
        get: operations["v1_projects_readiness_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{id}/takedown/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description T2 partner.site_takedown: {domain} route → 410. */
        post: operations["v1_sites_takedown_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Record the operator's Caddy-ownership decision. Never writes dns_zone. */
        patch: operations["v1_sites_partial_update"];
        trace?: never;
    };
    "/api/v1/sites/{site_id}/backups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET: metadata-only dumps plus the restore command block. */
        get: operations["v1_sites_backups_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/backups/{unit_id}/test/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST: seal a dump with BACKUP_KEY, persist Hub-local, return metadata. */
        post: operations["v1_sites_backups_test_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/env/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET names; PUT replaces / PATCH merges values; POST applies the current env. */
        get: operations["v1_sites_env_retrieve"];
        /** @description GET names; PUT replaces / PATCH merges values; POST applies the current env. */
        put: operations["v1_sites_env_update"];
        /** @description GET names; PUT replaces / PATCH merges values; POST applies the current env. */
        post: operations["v1_sites_env_create"];
        delete?: never;
        options?: never;
        head?: never;
        /** @description GET names; PUT replaces / PATCH merges values; POST applies the current env. */
        patch: operations["v1_sites_env_partial_update"];
        trace?: never;
    };
    "/api/v1/sites/{site_id}/manifest/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description POST materializes version N+1; GET returns the latest frozen manifest. */
        get: operations["v1_sites_manifest_retrieve"];
        put?: never;
        /** @description POST materializes version N+1; GET returns the latest frozen manifest. */
        post: operations["v1_sites_manifest_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/rollback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST: roll the site back to its latest succeeded Deployment. */
        post: operations["v1_sites_rollback_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/wizard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET the question set and current answers; PATCH a partial answer set. */
        get: operations["v1_sites_wizard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description GET the question set and current answers; PATCH a partial answer set. */
        patch: operations["v1_sites_wizard_partial_update"];
        trace?: never;
    };
    "/api/v1/targets/{id}/delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description T1: two passkeys + recent WebAuthn touch + type-the-name. */
        post: operations["v1_targets_delete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/targets/{id}/ssh-rotate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description T1: two passkeys + recent WebAuthn touch + type-the-name, then rotate. */
        post: operations["v1_targets_ssh_rotate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/targets/{id}/terminate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description T1: two passkeys + recent WebAuthn touch + type-the-name, then AWS terminate. */
        post: operations["v1_targets_terminate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `ack` - ack
         *     * `resolve` - resolve
         *     * `accept_risk` - accept_risk
         * @enum {string}
         */
        ActionEnum: "ack" | "resolve" | "accept_risk";
        AttackState: {
            detail: string;
            finding_id: number;
            mode: string;
        };
        AwsConnect: {
            access_key_id: string;
            secret_access_key: string;
            /** @default us-east-1 */
            region: string;
        };
        AwsConnectResult: {
            account_id_last4: string;
            region: string;
        };
        AwsStatus: {
            connected: boolean;
            reason: string;
        };
        BackupDump: {
            id: number;
            bytes: number;
            digest: string;
            stored_at: string;
            status: string;
        };
        BackupList: {
            units: components["schemas"]["BackupUnit"][];
            restore_command: string;
        };
        BackupRun: {
            schema_version: number;
            unit_id: number;
            site_id: number;
            bytes: number;
            digest: string;
            stored_at: string;
        };
        BackupUnit: {
            id: number;
            kind: string;
            schedule: string;
            dumps: components["schemas"]["BackupDump"][];
        };
        CandidateTarget: {
            id: number;
            host: string;
            kind: string;
            tunnel: boolean;
        };
        CertRefusal: {
            detail: string;
            finding_id: number;
        };
        CloudflareConnect: {
            token: string;
        };
        CloudflareConnectResult: {
            account: components["schemas"]["DnsAccountConnected"];
            zone: components["schemas"]["DnsZoneConnected"];
        };
        Confirm: {
            otp_code: string;
        };
        ConfirmName: {
            confirm_name: string;
        };
        DemoJob: {
            name: string;
            /**
             * Format: double
             * @default 0.5
             */
            delay: number;
            /** @default false */
            confirm_warnings: boolean;
        };
        DestinationRank: {
            destination_order: number[];
        };
        DnsAccountConnected: {
            readonly id: number;
            provider?: components["schemas"]["ProviderEnum"];
            label: string;
        };
        DnsZoneConnected: {
            readonly id: number;
            name: string;
            provider_zone_id?: string;
            purpose?: components["schemas"]["PurposeEnum"];
        };
        /**
         * @description * `host_caddy` - Host Caddy
         *     * `site_caddy` - Site Caddy
         * @enum {string}
         */
        EdgeOwnerEnum: "host_caddy" | "site_caddy";
        EnvApply: {
            deployment_id: number;
        };
        EnvNames: {
            names: string[];
            config_stale: boolean;
        };
        EnvWrite: {
            /** @description name -> value. Values are write-only and stored in the vault. */
            env: {
                [key: string]: string;
            };
        };
        /**
         * @description * `public` - Public
         *     * `mesh_only` - Mesh Only
         * @enum {string}
         */
        ExposureEnum: "public" | "mesh_only";
        Finding: {
            readonly id: number;
            source_engine: string;
            severity: components["schemas"]["SeverityEnum"];
            entity: string;
            title: string;
            body?: string;
            fix_action?: string;
            state?: components["schemas"]["StateEnum"];
            /** Format: date-time */
            first_seen?: string;
            /** Format: date-time */
            last_seen?: string;
            fingerprint: string;
            accepted_reason?: string;
        };
        FindingDetailSnapshot: {
            seq: number;
            data: components["schemas"]["Finding"];
        };
        FindingListSnapshot: {
            seq: number;
            data: components["schemas"]["Finding"][];
        };
        FirstRunItem: {
            id: components["schemas"]["IdEnum"];
            applicable: boolean;
            done: boolean;
        };
        FirstRunProgress: {
            owns_home: boolean;
            items: components["schemas"]["FirstRunItem"][];
        };
        FirstRunSnapshot: {
            seq: number;
            data: components["schemas"]["FirstRunProgress"];
        };
        /**
         * @description * `enroll_target` - enroll_target
         *     * `connect_cloudflare` - connect_cloudflare
         *     * `plant_origin_ca` - plant_origin_ca
         *     * `add_project` - add_project
         * @enum {string}
         */
        IdEnum: "enroll_target" | "connect_cloudflare" | "plant_origin_ca" | "add_project";
        InstanceCreate: {
            confirm_name: string;
            host: string;
            zone: string;
            /** @default t3.micro */
            instance_type: string;
        };
        InstanceCreateCost: {
            /** Format: double */
            cost: number;
            cost_display: string;
        };
        InstanceCreateResult: {
            id: number;
            host: string;
            kind: string;
        };
        InstanceTerminate: {
            confirm_name: string;
        };
        IntakeStatus: {
            status: components["schemas"]["StatusEnum"];
            mode: components["schemas"]["ModeEnum"];
            configured: boolean;
            as_of?: string | null;
        };
        /**
         * @description * `zone` - zone
         *     * `host` - host
         *     * `container` - container
         *     * `hub` - hub
         *     * `edge` - edge
         * @enum {string}
         */
        KindEnum: "zone" | "host" | "container" | "hub" | "edge";
        Login: {
            username: string;
            password: string;
            otp_code?: string;
            webauthn?: unknown;
        };
        Manifest: {
            version: number;
            schema_version: number;
            body: unknown;
            scan_report_hash: string;
            /** Format: date-time */
            created_at: string;
        };
        MapEdge: {
            a: string;
            b: string;
            path: components["schemas"]["PathEnum"];
        };
        MapGraph: {
            nodes: components["schemas"]["MapNode"][];
            edges: components["schemas"]["MapEdge"][];
        };
        MapNode: {
            id: string;
            kind: components["schemas"]["KindEnum"];
            label: string;
            status: string;
            parent?: string;
        };
        MapSnapshot: {
            seq: number;
            data: components["schemas"]["MapGraph"];
        };
        Materialize: {
            /** @default false */
            confirm_warnings: boolean;
        };
        Me: {
            authenticated: boolean;
            username?: string;
            otp_enrolled?: boolean;
            webauthn_count?: number;
            totp_enrolled?: boolean;
            t1_available?: boolean;
        };
        /**
         * @description * `fake` - fake
         *     * `configured` - configured
         * @enum {string}
         */
        ModeEnum: "fake" | "configured";
        OriginCaPlant: {
            path: string;
        };
        OriginCaPlantResult: {
            planted: boolean;
        };
        PartnerCreate: {
            slug: string;
            /** @default  */
            name: string;
            confirm_name: string;
        };
        PartnerCreateResult: {
            id: number;
            slug: string;
            name: string;
            hubk: string;
            whsec: string;
        };
        PartnerDestination: {
            id: number;
            host: string;
            kind: string;
        };
        PartnerList: {
            partners: components["schemas"]["PartnerPublic"][];
            intake: components["schemas"]["IntakeStatus"];
            api_enabled: boolean;
            candidate_targets: components["schemas"]["CandidateTarget"][];
        };
        PartnerPublic: {
            id: number;
            slug: string;
            name: string;
            destination_order: number[];
            destinations: components["schemas"]["PartnerDestination"][];
            suspended: boolean;
            site_ids: number[];
        };
        PatchedAnswers: {
            /** @description question id -> answer. Partial sets are fine; the wizard saves as you go. */
            answers: {
                [key: string]: unknown;
            };
        };
        PatchedEnvWrite: {
            /** @description name -> value. Values are write-only and stored in the vault. */
            env?: {
                [key: string]: string;
            };
        };
        /** @description PATCH /api/v1/sites/{id}/ — {edge_owner} only (design note §7 I-edge). */
        PatchedSiteEdgeOwner: {
            edge_owner?: components["schemas"]["EdgeOwnerEnum"];
        };
        /**
         * @description * `public` - public
         *     * `mesh` - mesh
         * @enum {string}
         */
        PathEnum: "public" | "mesh";
        /** @description POST /api/v1/projects/ — Project + Site in one transaction (I-target). */
        ProjectCreate: {
            name: string;
            /** @default  */
            git_url: string;
            /** @default main */
            git_ref: string;
            /** @default  */
            local_path: string;
            /** @default  */
            domain: string;
            /** @default public */
            exposure: components["schemas"]["ExposureEnum"];
            /** @default true */
            proxied: boolean;
            dns_zone?: number | null;
            primary_target?: number | null;
        };
        ProjectSummary: {
            id: number;
            name: string;
            slug: string;
            /** Format: date-time */
            scanned_at: string | null;
            tiers: {
                [key: string]: number;
            };
            sites: components["schemas"]["SiteSummary"][];
        };
        /**
         * @description * `cloudflare` - Cloudflare
         *     * `route53` - Route53
         * @enum {string}
         */
        ProviderEnum: "cloudflare" | "route53";
        /**
         * @description * `prod` - Prod
         *     * `test` - Test
         * @enum {string}
         */
        PurposeEnum: "prod" | "test";
        Question: {
            id: string;
            prompt: string;
            kind: string;
            default?: unknown;
            choices?: string[];
            secret: boolean;
        };
        Readiness: {
            /** Format: date-time */
            scanned_at: string | null;
            modules: string[];
            summary: {
                [key: string]: unknown;
            };
            blockers: {
                [key: string]: unknown;
            }[];
            warnings: {
                [key: string]: unknown;
            }[];
            advice: {
                [key: string]: unknown;
            }[];
            pending_sandbox: {
                [key: string]: unknown;
            }[];
        };
        RollbackResult: {
            deployment_id: number;
            original_id: number;
            status: string;
        };
        /**
         * @description * `p1` - P1
         *     * `p2` - P2
         *     * `p3` - P3
         * @enum {string}
         */
        SeverityEnum: "p1" | "p2" | "p3";
        /** @description PATCH /api/v1/sites/{id}/ — {edge_owner} only (design note §7 I-edge). */
        SiteEdgeOwner: {
            edge_owner: components["schemas"]["EdgeOwnerEnum"];
        };
        SiteSummary: {
            id: number;
            name: string;
            domain: string;
            latest_manifest_version: number | null;
            manifest_current: boolean | null;
            cert_refusal?: components["schemas"]["CertRefusal"] | null;
            attack_state?: components["schemas"]["AttackState"] | null;
            edge_owner?: components["schemas"]["EdgeOwnerEnum"];
            scale_ready?: boolean;
        };
        SshRotate: {
            confirm_name: string;
        };
        /**
         * @description * `open` - Open
         *     * `acked` - Acked
         *     * `resolved` - Resolved
         *     * `accepted` - Accepted
         * @enum {string}
         */
        StateEnum: "open" | "acked" | "resolved" | "accepted";
        /**
         * @description * `degraded` - degraded
         *     * `error` - error
         * @enum {string}
         */
        StatusEnum: "degraded" | "error";
        TargetDelete: {
            confirm_name: string;
        };
        Transition: {
            action: components["schemas"]["ActionEnum"];
            /** @default  */
            reason: string;
        };
        WebAuthnLoginBegin: {
            username: string;
        };
        WizardState: {
            questions: components["schemas"]["Question"][];
            answered: {
                [key: string]: unknown;
            };
            blocking: {
                [key: string]: unknown;
            }[];
            warnings: {
                [key: string]: unknown;
            }[];
            can_materialize: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    auth_totp_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Confirm"];
                "application/x-www-form-urlencoded": components["schemas"]["Confirm"];
                "multipart/form-data": components["schemas"]["Confirm"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_totp_enroll_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_webauthn_login_begin_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebAuthnLoginBegin"];
                "application/x-www-form-urlencoded": components["schemas"]["WebAuthnLoginBegin"];
                "multipart/form-data": components["schemas"]["WebAuthnLoginBegin"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    demo_jobs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoJob"];
                "application/x-www-form-urlencoded": components["schemas"]["DemoJob"];
                "multipart/form-data": components["schemas"]["DemoJob"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    topics_snapshot_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_aws_connect_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AwsStatus"];
                };
            };
        };
    };
    v1_aws_connect_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AwsConnect"];
                "application/x-www-form-urlencoded": components["schemas"]["AwsConnect"];
                "multipart/form-data": components["schemas"]["AwsConnect"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AwsConnectResult"];
                };
            };
        };
    };
    v1_cloudflare_connect_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloudflareConnect"];
                "application/x-www-form-urlencoded": components["schemas"]["CloudflareConnect"];
                "multipart/form-data": components["schemas"]["CloudflareConnect"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudflareConnectResult"];
                };
            };
        };
    };
    v1_dns_accounts_origin_ca_plant_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OriginCaPlant"];
                "application/x-www-form-urlencoded": components["schemas"]["OriginCaPlant"];
                "multipart/form-data": components["schemas"]["OriginCaPlant"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriginCaPlantResult"];
                };
            };
        };
    };
    v1_findings_retrieve: {
        parameters: {
            query?: {
                entity?: string;
                /**
                 * @description * `p1` - P1
                 *     * `p2` - P2
                 *     * `p3` - P3
                 */
                severity?: "p1" | "p2" | "p3";
                /**
                 * @description * `open` - Open
                 *     * `acked` - Acked
                 *     * `resolved` - Resolved
                 *     * `accepted` - Accepted
                 */
                state?: "open" | "acked" | "resolved" | "accepted";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingListSnapshot"];
                };
            };
        };
    };
    v1_findings_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingDetailSnapshot"];
                };
            };
        };
    };
    v1_findings_transition_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transition"];
                "application/x-www-form-urlencoded": components["schemas"]["Transition"];
                "multipart/form-data": components["schemas"]["Transition"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingDetailSnapshot"];
                };
            };
        };
    };
    v1_first_run_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FirstRunSnapshot"];
                };
            };
        };
    };
    v1_instance_create_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceCreateCost"];
                };
            };
        };
    };
    v1_instance_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["InstanceCreate"];
                "multipart/form-data": components["schemas"]["InstanceCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceCreateResult"];
                };
            };
        };
    };
    v1_map_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapSnapshot"];
                };
            };
        };
    };
    v1_partner_api_kill_switch_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmName"];
                "application/x-www-form-urlencoded": components["schemas"]["ConfirmName"];
                "multipart/form-data": components["schemas"]["ConfirmName"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_partners_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerList"];
                };
            };
        };
    };
    v1_partners_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartnerCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["PartnerCreate"];
                "multipart/form-data": components["schemas"]["PartnerCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerCreateResult"];
                };
            };
        };
    };
    v1_partners_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerPublic"];
                };
            };
        };
    };
    v1_partners_destination_rank_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DestinationRank"];
                "application/x-www-form-urlencoded": components["schemas"]["DestinationRank"];
                "multipart/form-data": components["schemas"]["DestinationRank"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerPublic"];
                };
            };
        };
    };
    v1_partners_suspend_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmName"];
                "application/x-www-form-urlencoded": components["schemas"]["ConfirmName"];
                "multipart/form-data": components["schemas"]["ConfirmName"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerPublic"];
                };
            };
        };
    };
    v1_projects_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    v1_projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["ProjectCreate"];
                "multipart/form-data": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
        };
    };
    v1_projects_readiness_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    v1_sites_takedown_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmName"];
                "application/x-www-form-urlencoded": components["schemas"]["ConfirmName"];
                "multipart/form-data": components["schemas"]["ConfirmName"];
            };
        };
        responses: {
            /** @description No response body */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_sites_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSiteEdgeOwner"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSiteEdgeOwner"];
                "multipart/form-data": components["schemas"]["PatchedSiteEdgeOwner"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteEdgeOwner"];
                };
            };
        };
    };
    v1_sites_backups_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupList"];
                };
            };
        };
    };
    v1_sites_backups_test_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
                unit_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupRun"];
                };
            };
        };
    };
    v1_sites_env_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvNames"];
                };
            };
        };
    };
    v1_sites_env_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["EnvWrite"];
                "multipart/form-data": components["schemas"]["EnvWrite"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvNames"];
                };
            };
        };
    };
    v1_sites_env_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvApply"];
                };
            };
        };
    };
    v1_sites_env_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEnvWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedEnvWrite"];
                "multipart/form-data": components["schemas"]["PatchedEnvWrite"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvNames"];
                };
            };
        };
    };
    v1_sites_manifest_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manifest"];
                };
            };
        };
    };
    v1_sites_manifest_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Materialize"];
                "application/x-www-form-urlencoded": components["schemas"]["Materialize"];
                "multipart/form-data": components["schemas"]["Materialize"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manifest"];
                };
            };
        };
    };
    v1_sites_rollback_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollbackResult"];
                };
            };
        };
    };
    v1_sites_wizard_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WizardState"];
                };
            };
        };
    };
    v1_sites_wizard_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAnswers"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAnswers"];
                "multipart/form-data": components["schemas"]["PatchedAnswers"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WizardState"];
                };
            };
        };
    };
    v1_targets_delete_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetDelete"];
                "application/x-www-form-urlencoded": components["schemas"]["TargetDelete"];
                "multipart/form-data": components["schemas"]["TargetDelete"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_targets_ssh_rotate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SshRotate"];
                "application/x-www-form-urlencoded": components["schemas"]["SshRotate"];
                "multipart/form-data": components["schemas"]["SshRotate"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_targets_terminate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceTerminate"];
                "application/x-www-form-urlencoded": components["schemas"]["InstanceTerminate"];
                "multipart/form-data": components["schemas"]["InstanceTerminate"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
