/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description CSRF-protected even though unauthenticated (round-1 finding: login-CSRF —
         *     a cross-site page must not be able to log the victim into an attacker account).
         *     The SPA fetches /api/auth/me/ on load, which plants the CSRF cookie.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Session hydration for the SPA. AllowAny: the anonymous response is the
         *     SPA's pre-login bootstrap and plants the CSRF cookie (get_token) so the
         *     login POST itself can be CSRF-checked.
         */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/totp/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_totp_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/totp/enroll/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_totp_enroll_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo-jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["demo_jobs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topic}/snapshot/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Snapshot-then-stream (§D7): every snapshot returns {seq, data} from the same counter. */
        get: operations["topics_snapshot_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description What the readiness screen renders its left column from (F7-lite).
         *
         *     tier COUNTS here, full check bodies from /readiness/ — the list stays cheap when
         *     projects grow. manifest_current answers the one freshness question the data model
         *     can answer honestly: does the latest manifest correspond to the CURRENT scan?
         *     (A true warnings-diff-since-last-manifest would need the prior report stored,
         *     which it isn't — noted in the F7 design decision rather than faked.)
         */
        get: operations["v1_projects_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/readiness/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The three-tier readiness report (§5.3), tiered server-side.
         *
         *     Tiering happens here rather than in the client so the CLI, the UI and the pipeline
         *     all agree on what counts as a blocker.
         */
        get: operations["v1_projects_readiness_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/manifest/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description POST materializes version N+1; GET returns the latest frozen manifest. */
        get: operations["v1_sites_manifest_retrieve"];
        put?: never;
        /** @description POST materializes version N+1; GET returns the latest frozen manifest. */
        post: operations["v1_sites_manifest_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/wizard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET the question set and current answers; PATCH a partial answer set. */
        get: operations["v1_sites_wizard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description GET the question set and current answers; PATCH a partial answer set. */
        patch: operations["v1_sites_wizard_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Confirm: {
            otp_code: string;
        };
        DemoJob: {
            name: string;
            /**
             * Format: double
             * @default 0.5
             */
            delay: number;
            /** @default false */
            confirm_warnings: boolean;
        };
        Login: {
            username: string;
            password: string;
            otp_code?: string;
        };
        Manifest: {
            version: number;
            schema_version: number;
            body: unknown;
            scan_report_hash: string;
            /** Format: date-time */
            created_at: string;
        };
        Materialize: {
            /** @default false */
            confirm_warnings: boolean;
        };
        PatchedAnswers: {
            /** @description question id -> answer. Partial sets are fine; the wizard saves as you go. */
            answers?: {
                [key: string]: unknown;
            };
        };
        ProjectSummary: {
            id: number;
            name: string;
            slug: string;
            /** Format: date-time */
            scanned_at: string | null;
            tiers: {
                [key: string]: number;
            };
            sites: components["schemas"]["SiteSummary"][];
        };
        Question: {
            id: string;
            prompt: string;
            kind: string;
            default?: unknown;
            choices?: string[];
            secret: boolean;
        };
        Readiness: {
            /** Format: date-time */
            scanned_at: string | null;
            modules: string[];
            summary: {
                [key: string]: unknown;
            };
            blockers: {
                [key: string]: unknown;
            }[];
            warnings: {
                [key: string]: unknown;
            }[];
            advice: {
                [key: string]: unknown;
            }[];
            pending_sandbox: {
                [key: string]: unknown;
            }[];
        };
        SiteSummary: {
            id: number;
            name: string;
            domain: string;
            latest_manifest_version: number | null;
            manifest_current: boolean | null;
        };
        WizardState: {
            questions: components["schemas"]["Question"][];
            answered: {
                [key: string]: unknown;
            };
            blocking: {
                [key: string]: unknown;
            }[];
            warnings: {
                [key: string]: unknown;
            }[];
            can_materialize: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_totp_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Confirm"];
                "application/x-www-form-urlencoded": components["schemas"]["Confirm"];
                "multipart/form-data": components["schemas"]["Confirm"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_totp_enroll_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    demo_jobs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoJob"];
                "application/x-www-form-urlencoded": components["schemas"]["DemoJob"];
                "multipart/form-data": components["schemas"]["DemoJob"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    topics_snapshot_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_projects_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    v1_projects_readiness_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    v1_sites_manifest_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manifest"];
                };
            };
        };
    };
    v1_sites_manifest_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Materialize"];
                "application/x-www-form-urlencoded": components["schemas"]["Materialize"];
                "multipart/form-data": components["schemas"]["Materialize"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manifest"];
                };
            };
        };
    };
    v1_sites_wizard_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WizardState"];
                };
            };
        };
    };
    v1_sites_wizard_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAnswers"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAnswers"];
                "multipart/form-data": components["schemas"]["PatchedAnswers"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WizardState"];
                };
            };
        };
    };
}
