"""core models package. Import from core.models — file location is not part of the API."""
from django.db.models.signals import pre_save

from .fleet import (
    AlertDelivery,
    AlertState,
    AuditChainHead,
    AuditEvent,
    BackupUnit,
    CheckRun,
    DnsAccount,
    DnsRecord,
    DnsZone,
    Finding,
    HostMetric,
    NetworkZone,
    OperationLock,
    Partner,
    PartnerApiFlag,
    PartnerIdempotencyKey,
    PartnerReplayNonce,
    PartnerSite,
    Project,
    RecoveryCode,
    Site,
    SiteInstance,
    SiteVolume,
    Target,
    TlsCertificate,
    TrafficStat,
    UptimeEvent,
    _default_checkrun_results,
)
from .hud import HudCommandOutbox, HudOperation
from .workspace import (
    Workspace,
    WorkspaceMembership,
    default_workspace,
    default_workspace_id,
    ensure_default_workspace_row,
    workspace_of,
)

for _model in (
    AlertState, AuditEvent, DnsAccount, Finding, NetworkZone, OperationLock, Partner,
    Project,
):
    pre_save.connect(ensure_default_workspace_row, sender=_model)

__all__ = [
    "_default_checkrun_results",
    "AlertDelivery",
    "AlertState",
    "AuditChainHead",
    "AuditEvent",
    "BackupUnit",
    "CheckRun",
    "DnsAccount",
    "DnsRecord",
    "DnsZone",
    "Finding",
    "HostMetric",
    "HudCommandOutbox",
    "HudOperation",
    "NetworkZone",
    "OperationLock",
    "Partner",
    "PartnerApiFlag",
    "PartnerIdempotencyKey",
    "PartnerReplayNonce",
    "PartnerSite",
    "Project",
    "RecoveryCode",
    "Site",
    "SiteInstance",
    "SiteVolume",
    "Target",
    "TlsCertificate",
    "TrafficStat",
    "UptimeEvent",
    "Workspace",
    "WorkspaceMembership",
    "default_workspace",
    "default_workspace_id",
    "workspace_of",
]
