# Generated by Django 5.2.17 on 2026-08-20 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], default='queued', max_length=16)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='deploys.manifest')),
                ('rollback_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollbacks', to='deploys.deployment')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_artifacts', to='deploys.deployment')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('name', models.CharField(choices=[('build', 'Build'), ('ship', 'Ship'), ('migrate', 'Migrate'), ('start_green', 'Start Green'), ('health_check', 'Health Check'), ('dns', 'Dns'), ('route_tls', 'Route Tls'), ('smoke_test', 'Smoke Test'), ('cutover', 'Cutover')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('log_text', models.TextField(blank=True, default='')),
                ('artifacts', models.JSONField(blank=True, default=dict)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='deploys.deployment')),
            ],
            options={
                'ordering': ['seq'],
                'constraints': [models.UniqueConstraint(fields=('deployment', 'seq'), name='uniq_deploymentstep_deployment_seq')],
            },
        ),
    ]
