# Generated by Django 5.2.17 on 2026-08-20 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_networkzone_site_config_stale_site_deploy_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(max_length=32)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_catalog_entries', to='core.target')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target', 'entry_id'), name='uniq_applied_catalog_target_entry')],
            },
        ),
    ]
