# Generated by Django 5.2.17 on 2026-08-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appliedcatalogentry',
            name='uniq_applied_catalog_target_entry',
        ),
    ]
