# Generated by Django 5.2.17 on 2026-08-08 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('env_bundle', 'Env Bundle'), ('ssh_private_key', 'Ssh Private Key'), ('tls_private_key', 'Tls Private Key'), ('cloud_credential', 'Cloud Credential'), ('api_token', 'Api Token')], max_length=32)),
                ('owner_type', models.CharField(max_length=32)),
                ('owner_id', models.CharField(max_length=64)),
                ('ciphertext', models.BinaryField()),
                ('wrapped_dek', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('algo', models.CharField(default='AES-256-GCM', max_length=32)),
                ('kek_id', models.CharField(max_length=64)),
                ('fingerprint', models.CharField(db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_type', 'owner_id'], name='vault_secre_owner_t_528d65_idx')],
            },
        ),
    ]
