# Generated by Django 5.2.17 on 2026-08-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='kind',
            field=models.CharField(choices=[('env_bundle', 'Env Bundle'), ('ssh_private_key', 'Ssh Private Key'), ('tls_private_key', 'Tls Private Key'), ('cloud_credential', 'Cloud Credential'), ('api_token', 'Api Token'), ('database_url', 'Database Url'), ('backup_key', 'Backup Key')], max_length=32),
        ),
    ]
